Repository CMPUT301W23T25/QR-Go-Gotta-Scan-Em-All, pull requests merged in 2023-03, with the labels that each got.

#55 Added fuctionailty to add pokemon to personal collection
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAdd.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QrScanner.java
  app/src/main/res/layout/activity_pokemon_add.xml
  app/src/main/res/layout/activity_qr_scanner.xml
Labels: story-point-2

#56 N devised
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Database.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAdd.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QrScanner.java
  app/src/main/res/menu/bottom_nav_bar.xml
Labels: bug

#57 Minor bug fixes
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAdd.java
Labels: bug

#59 Fixed Location permission request bug
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MapsActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAdd.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QrScanner.java
  app/src/main/res/layout/activity_maps.xml
Labels: bug

#62 General bug fixes
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QrScanner.java
Labels: Bug fixes

#65 Flow change
  app/build.gradle
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAdd.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QrScanner.java
  app/src/main/res/layout/activity_maps.xml
Labels: Bug fixes

#67 Initialized intent tests
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetDropDown.xml
  app/src/androidTest/java/com/example/qr_go_gotta_scan_em_all/ExampleInstrumentedTest.java
  app/src/androidTest/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivityTest.java
  app/src/androidTest/java/com/example/qr_go_gotta_scan_em_all/QrScannerActivityTest.java
Labels: documentation

#71 N devised
  .idea/androidTestResultsUserPreferences.xml
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Database.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Player.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PlayerIDGenerator.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/ProfilePageFragment.java
  app/src/main/res/layout/player_profile_view.xml
  app/src/main/res/layout/profile_page.xml
Labels: Bug fixes

#74 pokemon Add Activity changes
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
Labels: Bug fixes

#75 N devised
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonPlayerData.java
Labels: story-point-3

#79 Fixed some issues with added Scanned Pokemon being added into Overview.
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Player.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonArrayAdapter.java
  app/src/main/res/layout/content.xml
Labels: Bug fixes

#85 Fixed location issues
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Database.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LeaderboardArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LeaderboardFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MapsActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PlayerIDGenerator.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
Labels: Bug fixes

#86 Implemented some user stories such as lowest, highest scoring pokemon…
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/res/layout/overview_page.xml
  app/src/main/res/layout/profile_page.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: story-point-1, story-point-2

#116 Refactored code to allign with PokemonInformation class.
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Player.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonInformation.java
Labels: enhancement

#118 Reverted n devised2
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
Labels: story-point-5, Bug fixes

#120 Implemented Pokemon db functionality
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonInformation.java
Labels: story, Bug fixes

#122 Fixed bugged with loading pokemon from database into player collectio…
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
Labels: Bug fixes

#124 Reverted n devised2
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MapsActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
Labels: story

#125 Maps need fixing
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MapsActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
Labels: bug

#127 Added improved naming scheme
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Pokemon.java
Labels: enhancement, story

#129 fragments added for prep for qR search
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QRMoreInfoFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QRSearchFragment.java
  app/src/main/res/layout/fragment_q_r_more_info.xml
  app/src/main/res/layout/fragment_q_r_search.xml
Labels: story

#131 quality of life improvements
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QRSearchFragment.java
  app/src/main/res/layout/comment_delete_dialog.xml
  app/src/main/res/layout/content.xml
  app/src/main/res/layout/overview_list.xml
Labels: enhancement

#132 Major improvements and bugfixes. Layed down comments fragments, and also fixed the issue with images not loading from DB.
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/Comment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/CommentsArrayAdapter.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/LoginActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/QRMoreInfoFragment.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_comment_dialog.xml
  app/src/main/res/layout/content2.xml
  app/src/main/res/layout/fragment_q_r_more_info.xml
  app/src/main/res/layout/owners_dialog.xml
Labels: enhancement, story, Bug fixes

#133 Fixed bug of pokemon getting overridden if another user scans it
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonAddActivity.java
Labels: Bug fixes

#137 bug fixes with delete ruining images and location
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/OverviewFragment.java
Labels: Bug fixes

#138 Fix country name being null
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/MainActivity.java
  app/src/main/java/com/example/qr_go_gotta_scan_em_all/PokemonInformation.java
Labels: Bug fixes
